# Generated by Django 3.2.5 on 2021-12-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initial', 'initial'), ('in_progress', 'in_progress'), ('ready', 'ready'), ('finished', 'finished')], default='initial', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kakaoT.problem', verbose_name='problem')),
            ],
        ),
    ]
