# Generated by Django 3.2.5 on 2021-12-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoT', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='loc_col',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
